spring:
  application:
    name: blog-service
  task:
    execution:
      pool:
        max-size: 160
  r2dbc:
    url: r2dbc:mysql://localhost:3306/blog_service
    username: root
    password: password
    pool:
      max-size: 150
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    url: jdbc:mysql://localhost:3306/blog_service
    user: root
    password: password

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
