DROP TABLE IF EXISTS ARTICLE;

CREATE TABLE ARTICLE (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    category_id BIGINT UNIQUE NOT NULL,
    writer_id VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL ,
    content LONGTEXT NOT NULL ,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=INNODB CHARSET=UTF8MB4