DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    mapped_article_count BIGINT NOT NULL
) ENGINE=INNODB CHARSET=UTF8MB4